#!/bin/sh
# ==============================================================
# palmrun submit script for '<case>'
# Generated by palm_preproc - REVIEW BEFORE SUBMITTING.
# ==============================================================
# Core counts come from the processor topology chosen when this case was
# generated, so -X and -T always match the npex/npey in the _p3d files:
#
#   -X  total MPI processes  (parent + all nested children)
#   -T  MPI processes per node (must match the cluster's cores per node)
#   -t  WALL-CLOCK limit in seconds - this is the batch time limit, NOT the
#       simulated period (that is end_time in the _p3d file)
#   -r  run identifier: the JOBS/<id> directory palmrun works in
#   -c  palmrun configuration file (.ifx)
#   -a  activation string: which input/output files palmrun stages
#         d3#      main run (initial)
#         d3f      follow-up (restart) run
#         restart  also stage the restart files
#   -q  batch queue
#   -b  batch mode   -k  keep the temporary directory   -B  keep batch files
#
# To submit a restart continuation instead of the initial run, change
# -a "d3# restart" to -a "d3f restart" and use the _p3dr namelists.
# ==============================================================

# '<case>' main run
./bin/palmrun -b -k -r <palmrun_id> -c <palmrun_config> -a "<palmrun_activation>" -t <walltime_s> -X <total_cores> -T <node_cpus> -B -q <queue>
