"""Domain report generation for palm_preproc.

Writes a SHORT plain-text description of the case simulation: a compact
per-domain summary, the nesting validation (child offset llx/lly,
containment, clearance >= 2 parent cells, integer GSR <= 5), a minimal
&nesting_parameters block and the parent/child summary table. The full
machine-usable parameter sets now live in the files generated by the
`templates` stage (pgem_*.yaml, pmeteo_*.yaml, *_p3d/_p3dr).

The report is regenerated on every run (it is cheap and depends on the
`report:` config section, which is excluded from the resume-state hash so
changing npes etc. does not invalidate the pipeline state).
"""

from datetime import datetime
from pathlib import Path

from .domains import npe, valid_pairs
from ..log import get_logger

log = get_logger()


# ------------------------------
# 1. PER-DOMAIN SECTION
# ------------------------------
def _domain_section(spec, topology_opt):
    """Compact one-domain summary (details live in the generated files)."""
    L = [f"---- DOMAIN: {spec.name} ----"]
    L.append(f"{'  extent:':<16}{spec.width_m:.0f} x {spec.height_m:.0f} m "
             f"({spec.width_pts} x {spec.height_pts} pts @ {spec.grid_size:g} m)")
    L.append(f"{'  PALM nx/ny:':<16}nx = {spec.nx}, ny = {spec.ny}")
    L.append(f"{'  origin:':<16}origin_x = {spec.origin_x:.3f}, "
             f"origin_y = {spec.origin_y:.3f}  ({spec.crs})")
    pairs = valid_pairs(spec.width_pts, spec.height_pts, topology_opt)
    L.append(f"{'  decompositions:':<16}{len(pairs)} valid (opt={topology_opt})")
    L.append("")
    return L


# ------------------------------
# 2. NESTING VALIDATION (ported from palm_comp_nesting_param_final.py)
# ------------------------------
def _npes_from(topology, cfg):
    """Core counts for the namelist block: prefer the topology actually
    chosen in the templates stage; fall back to the targets in
    templates.values; '<npes>' placeholder when neither is known."""
    tv = cfg["templates"]["values"]
    t = topology or {}

    def one(side):
        if t.get(f"npex_{side}") and t.get(f"npey_{side}"):
            return t[f"npex_{side}"] * t[f"npey_{side}"]
        return tv.get(f"npes_{side}") or "<npes>"
    return {"parent": one("parent"), "child": one("child")}


def _nesting_section(child, parent, rcfg, npes, strict=True):
    L, warnings, errors = [], [], []

    llx_raw = child.origin_x - parent.origin_x
    lly_raw = child.origin_y - parent.origin_y
    llx = round(round(llx_raw / parent.grid_size) * parent.grid_size, 6)
    lly = round(round(lly_raw / parent.grid_size) * parent.grid_size, 6)

    L.append("---- NESTING ----")
    L.append(f"{'child offset llx:':<28}{llx:.3f} m"
             + ("" if abs(llx - llx_raw) < 1e-6
                else f"  (snapped from {llx_raw:.3f})"))
    L.append(f"{'child offset lly:':<28}{lly:.3f} m"
             + ("" if abs(lly - lly_raw) < 1e-6
                else f"  (snapped from {lly_raw:.3f})"))
    if abs(llx - llx_raw) > 1e-6 or abs(lly - lly_raw) > 1e-6:
        msg = (f"Child origin is OFF the parent lattice by "
               f"({llx - llx_raw:+.6f}, {lly - lly_raw:+.6f}) m: the child "
               f"static-driver content would be displaced relative to the "
               f"nest position PALM derives from domain_layouts.")
        (errors if strict else warnings).append(msg)

    # Offset must be non-negative
    if llx < 0:
        errors.append(f"llx = {llx:.1f} m is negative - child origin west of parent SW corner.")
    if lly < 0:
        errors.append(f"lly = {lly:.1f} m is negative - child origin south of parent SW corner.")

    # Child must fit inside parent
    x_end, y_end = llx + child.width_m, lly + child.height_m
    if x_end > parent.width_m:
        errors.append(f"Child exceeds parent in x: {x_end:.1f} > {parent.width_m:.1f} m.")
    if y_end > parent.height_m:
        errors.append(f"Child exceeds parent in y: {y_end:.1f} > {parent.height_m:.1f} m.")

    # Minimum clearance: at least 2 parent cells on each side
    min_clear = 2 * parent.grid_size
    for side, dist in (("west", llx), ("east", parent.width_m - x_end),
                       ("south", lly), ("north", parent.height_m - y_end)):
        L.append(f"{f'clearance {side}:':<28}{dist:.1f} m")
        if 0 <= dist < min_clear:
            warnings.append(f"Clearance on the {side} side ({dist:.1f} m) "
                            f"< 2 x parent_dx ({min_clear:.1f} m).")

    # Grid-spacing ratio: integer, <= 5
    gsr = parent.grid_size / child.grid_size
    L.append(f"{'GSR (parent_dx/child_dx):':<28}{gsr:g}")
    if abs(gsr - round(gsr)) > 1e-6:
        warnings.append(f"GSR ({gsr:.4f}) is not an integer - PALM requires integer GSR.")
    elif gsr > 5:
        warnings.append(f"GSR ({gsr:.0f}) exceeds the recommended maximum of 5.")

    for msg in warnings:
        L.append(f"  [WARNING] {msg}")
    for msg in errors:
        L.append(f"  [ERROR]   {msg}")
    if not warnings and not errors:
        L.append("All nesting checks passed.")
    L.append("")

    # &nesting_parameters block
    pname, cname = rcfg["parent_name"], rcfg["child_name"]
    npes_p, npes_c = npes["parent"], npes["child"]
    name_w = max(len(pname), len(cname)) + 2
    npes_w = max(len(str(npes_p)), len(str(npes_c)))
    ll_w = max(len(f"{llx:.1f}"), len(f"{lly:.1f}"), len("0.0"))

    def row(name, dom_id, par_id, npes, x, y):
        return (f"'{name}'{',' + ' ' * (name_w - len(name) - 1)}"
                f" {dom_id:>2},  {par_id:>2}, {npes:>{npes_w}}, "
                f"{x:>{ll_w}.1f}, {y:>{ll_w}.1f},")

    indent = " " * 21
    L.append("---- &nesting_parameters ----")
    L.append("(columns: name, domain id, parent id, npes, llx, lly --")
    L.append(" see README for details and optional parameters)")
    L.append(" &nesting_parameters")
    L.append(f"    domain_layouts = {row(pname, 1, -1, npes_p, 0.0, 0.0)}")
    L.append(f"{indent}{row(cname, 2, 1, npes_c, llx, lly)}")
    L.append(" /")
    L.append("")
    return L, warnings, errors, (llx, lly, gsr)


# ------------------------------
# 3. SUMMARY TABLE
# ------------------------------
def _summary_table(child, parent, rcfg, npes, llx, lly, gsr):
    L = []
    L.append("-" * 62)
    L.append(f"{'Field':<30} {'Parent':>14} {'Child':>14}")
    L.append("-" * 62)
    rows = [
        ("domain name", rcfg["parent_name"], rcfg["child_name"]),
        ("domain id", 1, 2),
        ("parent id", -1, 1),
        ("npes", npes["parent"], npes["child"]),
        ("origin_x [m]", f"{parent.origin_x:.3f}", f"{child.origin_x:.3f}"),
        ("origin_y [m]", f"{parent.origin_y:.3f}", f"{child.origin_y:.3f}"),
        ("nx (PALM)", parent.nx, child.nx),
        ("ny (PALM)", parent.ny, child.ny),
        ("dx = dy [m]", f"{parent.grid_size:g}", f"{child.grid_size:g}"),
        ("domain extent x [m]", f"{parent.width_m:.1f}", f"{child.width_m:.1f}"),
        ("domain extent y [m]", f"{parent.height_m:.1f}", f"{child.height_m:.1f}"),
        ("lower_left_x (llx) [m]", "0.0", f"{llx:.1f}"),
        ("lower_left_y (lly) [m]", "0.0", f"{lly:.1f}"),
        ("GSR (parent_dx/child_dx)", "-", f"{gsr:g}"),
    ]
    for name, p, c in rows:
        L.append(f"{name:<30} {p!s:>14} {c!s:>14}")
    L.append("-" * 62)
    return L


# ------------------------------
# 4. REPORT WRITER
# ------------------------------
def write_domain_report(child, parent, cfg, out_path=None, topology=None):
    """Assemble and write the domain report. Returns the report path."""
    rcfg = cfg["report"]
    out_path = Path(out_path or rcfg["file"] or
                    cfg.output_dir / "domains_report.txt")

    L = []
    L.append("=" * 62)
    L.append(f" palm_preproc domain report | project "
             f"'{cfg['project']['name']}'")
    L.append(f" generated: {datetime.now().isoformat(timespec='seconds')}")
    _src, _kind = cfg.domain_source()
    L.append(f" domain input: {_src}"
             + ("" if _kind == "domain" else "  (layer extent)"))
    L.append("=" * 62)
    L.append("")

    topo_opt = cfg["domains"]["parent"].get("topology_opt", True)
    strict = cfg["domains"].get("strict_nesting", True)
    L += _domain_section(child, topo_opt)
    L += _domain_section(parent, topo_opt)

    npes = _npes_from(topology, cfg)
    nest_lines, warnings, errors, (llx, lly, gsr) = _nesting_section(
        child, parent, rcfg, npes, strict)
    L += nest_lines
    L += _summary_table(child, parent, rcfg, npes, llx, lly, gsr)
    L.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(L))

    for msg in warnings:
        log.warning(f"report: {msg}")
    for msg in errors:
        log.error(f"report: {msg}")
    log.debug(f"written: {out_path}")
    if errors:
        raise RuntimeError(
            f"Nesting validation failed with {len(errors)} error(s); "
            f"see {out_path} and the log above."
        )
    return out_path
